CREATE DATABASE MESADINHA;
USE MESADINHA;

CREATE TABLE USUARIO(
ID INT UNSIGNED NOT NULL PRIMARY KEY,
NOME VARCHAR(80) NOT NULL,
ENDERECO VARCHAR(150) NOT NULL,
TELEFONE CHAR(15) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
SENHA VARCHAR(30) NOT NULL
)ENGINE=INNODB;


CREATE TABLE CATEGORIA(
ID INT UNSIGNED NOT NULL PRIMARY KEY,
NOME VARCHAR(80) NOT NULL
)ENGINE=INNODB;

CREATE TABLE CONTA(
ID INT UNSIGNED NOT NULL PRIMARY KEY,
NOME VARCHAR(80) NOT NULL,
TIPO INT NOT NULL,
CATEGORIA_ID VARCHAR(50) NOT NULL,
FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(ID)
)ENGINE=INNODB;

CREATE TABLE MOVIMENTACAO(
ID INT UNSIGNED NOT NULL PRIMARY KEY,
VALOR INT NOT NULL,
CONTA_ID VARCHAR(50) NOT NULL,
FOREIGN KEY (CONTA_ID) REFERENCES CONTA(ID)
)ENGINE=INNODB;